### ISSUE TITLE
[Feature Request] Add a flag to disable the generation of `.env.enc.readable`

### ISSUE THREAD

**Issue by Saeid-Za** [tka85/dotenvenc#10]
Hello !
Since the version `5.2.0` there is an additional file generated on encryption.

> Each time you encrypt your .env now you get additionally to the .env.enc also a file .env.enc.readable (or if you are using a custom env file, the same named with a .enc.readable suffix). This file contains the variable names in human readable form, and the values are the HMAC digests of the corresponding .env values. Why? So that you can see each time you re-generate the encrypted .env.enc, which variables have potentially changed.

Since in many scenarios we don't really need the diffing functionality, I'd like to suggest adding a flag to disable the generation of `.env.enc.readable`

The current workaround is to lock the version to `5.1.x`

**Comment by tka85** [comment]
Agreed. Also felt a bit funny with getting it generated by default.

Adding a flag `-r` additionally to `-e` when you encrypt the file. Only then will the additional, semi-readable `.readable` be added. Otherwise it will be the same behavior as pre-5.2.0.

**Comment by tka85** [comment]
Fixed in v5.3.0

**Comment by tka85** [comment]
Fixed in v5.3.0
