### ISSUE TITLE
[Feature Request] Disable log output (silent mode)

### ISSUE THREAD

**Issue by cp-fabian-pittroff** [tka85/dotenvenc#13]
Hello,
first of all, thank you for this tool. I'm currently using it for playwright tests and have a suggestion. Would it be possible to remove the `console.log` message `# Decrypted using env variable DOTENVENC_PASS`? Maybe with some kind of silent flag, to disable it.

The reason for this is that playwright executes dotenvenc for every single test and thus clutters up the console.

**logs:**
```shell
Running 90 tests using 6 workers

# Decrypted using env variable DOTENVENC_PASS
# Decrypted using env variable DOTENVENC_PASS
# Decrypted using env variable DOTENVENC_PASS
# Decrypted using env variable DOTENVENC_PASS
# Decrypted using env variable DOTENVENC_PASS
# Decrypted using env variable DOTENVENC_PASS
...
```

**Comment by luchsamapparat** [comment]
I have exactly the same issue! Would a PR for this be accepted?

**Comment by tka85** [comment]
@cp-fabian-pittroff  Apologies for the delayed response.

CLI param `--silent` / `-s` has been added. You can find it in published package version @5.4.1

It suppresses all non-error messages.

**Comment by luchsamapparat** [comment]
Works like a charm. Thank you!

**Comment by cp-fabian-pittroff** [comment]
@tka85 Thanks for implementing. Works perfectly.
