### ISSUE TITLE
Can't enter password at command prompt

### ISSUE THREAD

**Issue by evanduser** [tka85/dotenvenc#7]
Running dotenvenc pulling password from command prompt aborts program.
ie  node server.js   DOESN"T WORK, asks for password, but just aborts.

 DOTENVENC_PASS='mypassword' node server.js does work but leaves password in env variable

Also as a side note web docs are incorrect. For node the require statement is:
require('@tka85/dotenvenc').decrypt();
not:
require('dotenvenc').decrypt();

**Comment by tka85** [comment]
Ok. Several issues here.

When you say `DOESN"T WORK, asks for password, but just aborts.` do you mean it crashes with an error message that says `Restored no env variables. Either empty input file or wrong password.`? Then, assuming you are using a non-empty input file, you are probably giving the wrong password.

You can test it yourself using the dotenv file `.env.sample.enc` used by the unit tests. The password is `superDuperPassword`:

```
unset DOTENVENC_PASS;             # in case you had an env variable set previously
./bin/dotenvenc -d -i ./test/.env.sample.enc
✔ Type password: … ******************
ALPHA=bar
BETA=foo bar
GAMMA=1234
DELTA=With \"double quotes\" inside
DELTA_2=With 'single quotes' inside
EPSILON=bla
KAPPA=multi
line
value
```

Check that you have the correct password. Before that also check you are creating the encrypted file from your dotenv correctly. For example:

```
./bin/dotenvenc -e -i .mydotenvenc -o .mydotenvenc.enc
```

Regarding the `DOTENVENC_PASS='mypassword' node server.js does work but leaves password in env variable`, I try it and again it works fine:

```
DOTENVENC_PASS=superDuperPassword ./bin/dotenvenc -d -i ./test/.env.sample.enc
echo $DOTENVENC_PASS        # returns nothing
```


Thank you for the README correction. Will fix asap.
