### ISSUE TITLE
Using Decrypted Value in Native Level

### ISSUE THREAD

**Issue by evanedsaazola** [tka85/dotenvenc#8]
Hi, 

Just started using the package and I think it's a wonderful package to help securing the secrets in the application.

But, there are some questions that i had in mind, wondering if this possible to do in the package or not. 

Let's just say that I have token that already in the .env.enc file, and now I want to decrypt it to use the encrypted value. But I need to use it in the native level _(for example, need to use the value in the AndroidManifest.xml for Android and AppDelegate.mm for iOS)_. 

From the docs it seems only shows the way to decrypt in Javascript files. So I wondering is it possible to use the decrypted value inside those files in native level? 

Really hope getting the answers for this question. Thank you for the help in advance :)

**Comment by tka85** [comment]
This is an npm package. You cannot use it, to my knowledge, in an Android project.
